#!/bin/bash
# Diagnóstico completo de Conflict Zero

echo "══════════════════════════════════════════════════════════"
echo "🔍 DIAGNÓSTICO RENDER - CONFLICT ZERO"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "PROBLEMA: El servicio está 'Live' pero con código antiguo"
echo ""
echo "══════════════════════════════════════════════════════════"
echo "📋 VERIFICACIONES EN RENDER (Haz esto ahora):"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "【1】VERIFICAR CONEXIÓN A GITHUB"
echo "──────────────────────────────────────────────────────────"
echo "Ve a: https://dashboard.render.com/ → conflict-zero-api"
echo "Pestaña: 'Settings' → 'Build & Deploy'"
echo "Verifica que diga:"
echo "  Repository: Chuos24/conflict-zero"
echo "  Branch: main"
echo ""
echo "【2】VERIFICAR ÚLTIMO DEPLOY"
echo "──────────────────────────────────────────────────────────"
echo "En el mismo lugar, revisa:"
echo "  'Last Deployed:' ¿Es reciente? (últimos minutos)"
echo "  'Deploy Status:' ¿Dice 'Success'?"
echo ""
echo "Si el último deploy es viejo (horas atrás), el auto-deploy falló."
echo ""
echo "【3】FORZAR DEPLOY MANUAL"
echo "──────────────────────────────────────────────────────────"
echo "Si el deploy no es reciente:"
echo "  1. Ve a la pestaña 'Manual Deploy'"
echo "  2. Selecciona: 'Deploy latest commit'"
echo "  3. O: 'Clear build cache & deploy'"
echo ""
echo "【4】VERIFICAR LOGS DE BUILD"
echo "──────────────────────────────────────────────────────────"
echo "Ve a la pestaña 'Logs'"
echo "Busca errores como:"
echo "  - 'Failed to fetch from GitHub'"
echo "  - 'Merge conflict'"
echo "  - 'Build failed'"
echo ""
echo "══════════════════════════════════════════════════════════"
echo "🔧 SOLUCIÓN RÁPIDA (Si el auto-deploy no funciona)"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "OPCIÓN A: Reconectar GitHub"
echo "  1. Settings → 'Build & Deploy'"
echo "  2. Click 'Disconnect' (si aparece)"
echo "  3. Click 'Connect' → Selecciona 'conflict-zero'"
echo "  4. Deploy automático"
echo ""
echo "OPCIÓN B: Deploy manual desde GitHub"
echo "  1. Ve a https://github.com/Chuos24/conflict-zero"
echo "  2. Settings → Webhooks → Add webhook"
echo "  3. Payload URL: (la URL de deploy de Render)"
echo ""
echo "OPCIÓN C: Crear nuevo servicio"
echo "  1. Borra el servicio actual (Settings → Delete)"
echo "  2. New Web Service → Connect GitHub"
echo "  3. Selecciona conflict-zero"
echo "  4. Configura como Starter"
echo ""
echo "══════════════════════════════════════════════════════════"
echo ""
echo "¿Qué dice tu último deploy en Render? ¿Es reciente?"
echo ""
