#!/bin/bash
# Script para verificar y forzar redeploy

echo "═══════════════════════════════════════════"
echo "🔧 FORZAR REDEPLOY EN RENDER"
echo "═══════════════════════════════════════════"
echo ""
echo "Sigue estos pasos:"
echo ""
echo "1. Ve a: https://dashboard.render.com/"
echo ""
echo "2. Click en 'conflict-zero-api'"
echo ""
echo "3. Ve a la pestaña 'Environment'"
echo ""
echo "4. VERIFICA que existe:"
echo "   DATABASE_URL = (tu URL de postgres)"
echo ""
echo "5. Si no existe, agrégala AHORA:"
echo "   - Click 'Add Environment Variable'"
echo "   - Key: DATABASE_URL"
echo "   - Value: (copia desde conflict-zero-db)"
echo ""
echo "6. Guarda: Click 'Save Changes'"
echo ""
echo "7. Espera 30 segundos..."
echo ""
echo "8. Ve a la pestaña 'Logs'"
echo "   Busca: 'Usuario founder creado'"
echo ""
echo "9. Prueba login en tu frontend de Netlify"
echo ""
echo "═══════════════════════════════════════════"
