#!/bin/bash
# Forzar rebuild completo en Render

echo "══════════════════════════════════════════════════════════"
echo "🔄 FORZAR REBUILD COMPLETO EN RENDER"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "El deploy es reciente (10 min) pero el código no se actualizó."
echo "Esto indica un problema de caché o build."
echo ""
echo "══════════════════════════════════════════════════════════"
echo "📋 PASOS PARA SOLUCIONAR:"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "【OPCIÓN 1】Clear Build Cache (Recomendado)"
echo "──────────────────────────────────────────────────────────"
echo "1. Ve a: https://dashboard.render.com/"
echo "2. Click en: conflict-zero-api"
echo "3. Pestaña: 'Settings'"
echo "4. Scroll hasta abajo"
echo "5. Click en: 'Clear build cache & deploy'"
echo "6. Esperar 5 minutos completos"
echo "7. Verificar en Logs que diga 'Build successful'"
echo ""
echo "【OPCIÓN 2】Cambiar variable de entorno para forzar rebuild"
echo "──────────────────────────────────────────────────────────"
echo "1. Ve a: conflict-zero-api → Environment"
echo "2. Agrega una variable dummy:"
echo "   Key: REBUILD"
echo "   Value: 1"
echo "3. Guardar (esto forzará redeploy automático)"
echo "4. Esperar 5 minutos"
echo "5. (Opcional: borrar la variable después)"
echo ""
echo "【OPCIÓN 3】Borrar y recrear el servicio"
echo "──────────────────────────────────────────────────────────"
echo "Si las opciones 1 y 2 fallan:"
echo ""
echo "1. Ve a conflict-zero-api → Settings"
echo "2. Scroll abajo → 'Delete Service'"
echo "3. Confirmar borrado"
echo "4. Click 'New +' → 'Web Service'"
echo "5. Conectar GitHub → Seleccionar conflict-zero"
echo "6. Configurar:"
echo "   Name: conflict-zero-api"
echo "   Runtime: Python 3"
echo "   Build Command: cd backend && pip install -r requirements.txt"
echo "   Start Command: cd backend && uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo "   Plan: Starter"
echo "7. Environment Variables:"
echo "   PERU_API_KEY = d02bb5a71984e759885a4e47a575715c"
echo "8. Create Web Service"
echo ""
echo "══════════════════════════════════════════════════════════"
echo "✅ VERIFICACIÓN DESPUÉS DEL DEPLOY"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "Una vez que termine el deploy, verifica:"
echo ""
echo "1. Abre en navegador:"
echo "   https://conflict-zero-api.onrender.com/api/v1/auth/setup/create-founder"
echo ""
echo "2. Debería decir (o usuario ya existe):"
echo '   {"message":"Usuario founder creado exitosamente",...}'
echo ""
echo "3. Si sigue diciendo 'password cannot be longer than 72 bytes',"
echo "   significa que el código NO se actualizó."
echo ""
echo "══════════════════════════════════════════════════════════"
echo ""
echo "¿Intentas la OPCIÓN 1 primero (Clear build cache)?"
echo ""
