#!/bin/bash
# PASOS PARA RECREAR EL SERVICIO EN RENDER

echo "══════════════════════════════════════════════════════════"
echo "🔥 SOLUCIÓN NUCLEAR: Recrear servicio en Render"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "PROBLEMA: Render está usando código viejo (commit f5960d2)"
echo "SOLUCIÓN: Borrar y crear servicio nuevo desde cero"
echo ""
echo "══════════════════════════════════════════════════════════"
echo "📋 PASOS:"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "【1】BORRAR SERVICIO ACTUAL"
echo "──────────────────────────────────────────────────────────"
echo "1. Ve a: https://dashboard.render.com/"
echo "2. Click en tu servicio 'conflict-zero-api'"
echo "3. Pestaña 'Settings'"
echo "4. Scroll abajo hasta 'Delete Service'"
echo "5. Escribe el nombre para confirmar"
echo "6. Click 'Delete Service'"
echo ""
echo "【2】CREAR NUEVO SERVICIO"
echo "──────────────────────────────────────────────────────────"
echo "1. Click azul 'New +' (arriba a la derecha)"
echo "2. Selecciona 'Web Service'"
echo "3. Conecta tu cuenta de GitHub"
echo "4. Busca y selecciona: 'conflict-zero'"
echo "5. Configura:"
echo ""
echo "   Name: conflict-zero-api"
echo "   Region: Oregon (US West)"
echo "   Branch: main"
echo "   Runtime: Python 3"
echo "   Build Command: cd backend && pip install -r requirements.txt"
echo "   Start Command: cd backend && uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo "   Plan: Starter ($7/mo)"
echo ""
echo "【3】VARIABLES DE ENTORNO"
echo "──────────────────────────────────────────────────────────"
echo "Agrega estas variables:"
echo ""
echo "   PERU_API_KEY = d02bb5a71984e759885a4e47a575715c"
echo "   DATABASE_URL = (deja vacío, se llena automáticamente con la DB)"
echo "   SECRET_KEY = (deja vacío, Render genera uno)"
echo "   ENVIRONMENT = production"
echo "   DEBUG = false"
echo ""
echo "【4】CREAR BASE DE DATOS (si no existe)"
echo "──────────────────────────────────────────────────────────"
echo "1. Dashboard → 'New +' → 'PostgreSQL'"
echo "2. Name: conflict-zero-db"
echo "3. Plan: Starter"
echo "4. Region: Oregon (misma que el servicio)"
echo "5. Create Database"
echo "6. Vuelve al servicio web y conecta la DB en Environment"
echo ""
echo "【5】DEPLOY"
echo "──────────────────────────────────────────────────────────"
echo "1. Click 'Create Web Service'"
echo "2. Espera 5-10 minutos"
echo "3. Verifica en logs que diga:"
echo '      "✅ Usuario founder creado exitosamente con contraseña CZ2025!"'
echo ""
echo "══════════════════════════════════════════════════════════"
echo "✅ DESPUÉS DEL DEPLOY"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "Prueba el endpoint:"
echo "   https://conflict-zero-api.onrender.com/api/v1/auth/setup/create-founder"
echo ""
echo "Debería responder:"
echo '   {"message":"Usuario founder creado exitosamente",...}'
echo ""
echo "══════════════════════════════════════════════════════════"
echo ""
