#!/bin/bash
# Script para configurar deploy en Render

echo "═══════════════════════════════════════════════"
echo "🚀 CONFIGURACIÓN RENDER - Conflict Zero"
echo "═══════════════════════════════════════════════"
echo ""
echo "📋 PASOS PARA COMPLETAR EL DEPLOY:"
echo ""
echo "1. Ve a: https://dashboard.render.com/blueprints"
echo ""
echo "2. Click en: 'New Blueprint Instance'"
echo ""
echo "3. Busca y selecciona tu repo: 'conflict-zero'"
echo ""
echo "4. Configura el nombre: 'conflict-zero-api'"
echo ""
echo "5. En 'Environment Variables', agrega:"
echo "   PERU_API_KEY = d02bb5a71984e759885a4e47a575715c"
echo "   SECRET_KEY = $(openssl rand -hex 32)"
echo "   ENVIRONMENT = production"
echo ""
echo "6. Click en 'Apply' y espera (~5 minutos)"
echo ""
echo "7. Cuando termine, copia la URL que te dan"
echo "   Será algo como: https://conflict-zero-api.onrender.com"
echo ""
echo "═══════════════════════════════════════════════"
echo ""
echo "¿Necesitas que te espere y actualice el frontend"
echo "cuando tengas la URL del backend?"
echo ""
