#!/bin/bash
# ÚLTIMA SOLUCIÓN: Recrear servicio Render desde cero

echo "══════════════════════════════════════════════════════════"
echo "🔥 SOLUCIÓN FINAL: Recrear servicio en Render"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "Render está usando código viejo (commit f5960d2)"
echo "en lugar del nuevo (commit da1d9c3 con hash pre-calculado)"
echo ""
echo "══════════════════════════════════════════════════════════"
echo "📋 PASOS PARA RECREAR:"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "【1】BORRAR SERVICIO ACTUAL"
echo "──────────────────────────────────────────────────────────"
echo "1. Ve a: https://dashboard.render.com/"
echo "2. Click en tu servicio"
echo "3. Settings → Delete Service"
echo "4. Confirmar borrado"
echo ""
echo "【2】CREAR NUEVO SERVICIO"
echo "──────────────────────────────────────────────────────────"
echo "1. Click 'New +' → 'Web Service'"
echo "2. Conecta GitHub → Selecciona 'conflict-zero'"
echo "3. Configuración:"
echo ""
echo "   Name: conflict-zero-api"
echo "   Region: Oregon"
echo "   Branch: main"
echo "   Runtime: Python 3"
echo "   Build Command: cd backend && pip install -r requirements.txt"
echo "   Start Command: cd backend && uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo "   Plan: Starter"
echo ""
echo "【3】VARIABLES DE ENTORNO (en la misma página)"
echo "──────────────────────────────────────────────────────────"
echo "Agrega estas variables ANTES de crear:"
echo ""
echo "   PERU_API_KEY = d02bb5a71984e759885a4e47a575715c"
echo "   ENVIRONMENT = production"
echo "   DEBUG = false"
echo ""
echo "【4】CREAR WEB SERVICE"
echo "──────────────────────────────────────────────────────────"
echo "1. Click 'Create Web Service'"
echo "2. Espera el deploy (5-10 minutos)"
echo "3. Verifica en logs:"
echo '      "✅ Usuario founder creado exitosamente con contraseña CZ2025!"'
echo ""
echo "══════════════════════════════════════════════════════════"
echo "🔗 URL FINAL"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "Tu backend estará en:"
echo "   https://conflict-zero-api.onrender.com"
echo ""
echo "Probar:"
echo "   https://conflict-zero-api.onrender.com/api/v1/auth/setup/create-founder"
echo ""
echo "══════════════════════════════════════════════════════════"
echo ""
