#!/bin/bash
# Script completo para verificar y solucionar problemas de Conflict Zero

echo "═══════════════════════════════════════════════════════════════"
echo "🔧 CONFLICT ZERO - SOLUCIÓN COMPLETA DE PROBLEMAS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "PROBLEMAS DETECTADOS:"
echo "  ❌ Error 401 - Credenciales incorrectas"
echo "  ❌ Error 403 - Posible problema de CORS/permisos"
echo "  ❌ Backend no actualizado con endpoint de founder"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📋 PASOS PARA SOLUCIONAR (Hacer en orden):"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "【PASO 1】FORZAR REDEPLOY EN RENDER"
echo "─────────────────────────────────────────────────────────────"
echo "1. Ve a: https://dashboard.render.com/"
echo "2. Click en 'conflict-zero-api'"
echo "3. Ve a Settings (pestaña)"
echo "4. Scroll abajo, click 'Clear build cache & deploy'"
echo "5. Espera 3-5 minutos hasta que diga 'Live'"
echo ""
echo "【PASO 2】VERIFICAR ENDPOINT DE FOUNDER"
echo "─────────────────────────────────────────────────────────────"
echo "Una vez que el deploy termine, prueba en navegador:"
echo ""
echo "  https://conflict-zero-api.onrender.com/api/v1/auth/setup/create-founder"
echo ""
echo "Debería responder:"
echo '  {"message":"Usuario founder creado exitosamente",...}'
echo ""
echo "【PASO 3】PROBAR LOGIN"
echo "─────────────────────────────────────────────────────────────"
echo "Después de crear el founder, prueba login con:"
echo ""
echo "  Email: founder@conflictzero.com"
echo "  Password: FounderPass2025!"
echo ""
echo "【PASO 4】SI SIGUE FALLANDO - OPCIÓN B"
echo "─────────────────────────────────────────────────────────────"
echo "Si el endpoint no funciona, usa el API directamente:"
echo ""
echo "curl -X POST https://conflict-zero-api.onrender.com/api/v1/auth/register \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"tuemail@ejemplo.com\",\"password\":\"TuPass123\",\"full_name\":\"Tu Nombre\",\"company_name\":\"Tu Empresa\",\"ruc\":\"20100100123\"}'"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🔍 DIAGNÓSTICO DE ERRORES"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Error 401: El usuario no existe o la contraseña es incorrecta"
echo "Solución: Crear usuario founder (paso 2) o registrar nuevo usuario"
echo ""
echo "Error 403: Problema de CORS o permisos"
echo "Solución: Verificar que el backend tenga CORS configurado (* ya está configurado)"
echo ""
echo "Error 404: Endpoint no existe"
echo "Solución: El deploy no se completó, repetir paso 1"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "¿Necesitas más ayuda? Revisa los logs en Render:"
echo "  https://dashboard.render.com/ → conflict-zero-api → Logs"
echo ""
echo "═══════════════════════════════════════════════════════════════"
