services:
  - type: static
    name: cz-certificados
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /certificado/:slug
        destination: /certificado-:slug.html
