"""add_company_snapshots_ml_ready

Revision ID: 5bf3fcd427a1
Revises: 
Create Date: 2026-03-28 00:48:18.036109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf3fcd427a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tabla company_snapshots (Time-series para ML)
    op.create_table(
        'company_snapshots',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('ruc', sa.String(11), nullable=False, index=True),
        sa.Column('snapshot_date', sa.DateTime(), nullable=False, index=True),
        
        # Datos SUNAT
        sa.Column('sunat_status', sa.String(20), nullable=True),
        sa.Column('sunat_debt', sa.Float(), default=0.0),
        sa.Column('sunat_num_trabajadores', sa.Integer(), nullable=True),
        sa.Column('sunat_ultimo_pago', sa.DateTime(), nullable=True),
        
        # Datos OSCE
        sa.Column('osce_inhabilitado', sa.Boolean(), default=False),
        sa.Column('osce_sanciones_count', sa.Integer(), default=0),
        sa.Column('osce_sanciones_vigentes', sa.Integer(), default=0),
        sa.Column('osce_sanciones_historicas', sa.Integer(), default=0),
        sa.Column('osce_ultima_sancion_fecha', sa.DateTime(), nullable=True),
        
        # Datos TCE
        sa.Column('tce_sanciones_count', sa.Integer(), default=0),
        sa.Column('tce_ultima_sancion_fecha', sa.DateTime(), nullable=True),
        
        # Features calculadas para ML
        sa.Column('dias_ultimo_pago', sa.Integer(), nullable=True),
        sa.Column('dias_ultima_sancion_osce', sa.Integer(), nullable=True),
        sa.Column('score_calculado', sa.Integer(), nullable=True),
        
        # Metadata
        sa.Column('source_api', sa.String(50), nullable=True),
        sa.Column('query_id', sa.String(36), sa.ForeignKey('verification_requests.id'), nullable=True),
        sa.Column('raw_data_hash', sa.String(64), nullable=True),
        sa.Column('created_at', sa.DateTime(), default=sa.func.now())
    )
    
    # Índice compuesto para consultas ML
    op.create_index('idx_snapshots_ruc_date', 'company_snapshots', ['ruc', 'snapshot_date'])
    
    # Tabla ml_training_logs (Placeholder para ML futuro)
    op.create_table(
        'ml_training_logs',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('model_version', sa.String(20), nullable=False),
        sa.Column('training_date', sa.DateTime(), default=sa.func.now()),
        sa.Column('dataset_size', sa.Integer(), nullable=False),
        sa.Column('accuracy', sa.Float(), nullable=True),
        sa.Column('precision', sa.Float(), nullable=True),
        sa.Column('recall', sa.Float(), nullable=True),
        sa.Column('f1_score', sa.Float(), nullable=True),
        sa.Column('feature_importance', sa.JSON(), default=dict),
        sa.Column('model_path', sa.String(500), nullable=True),
        sa.Column('is_active', sa.Boolean(), default=False),
        sa.Column('notes', sa.Text(), nullable=True)
    )
    
    # Tabla supplier_alerts (Alertas de cambios en proveedores)
    op.create_table(
        'supplier_alerts',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('supplier_ruc', sa.String(11), nullable=False, index=True),
        sa.Column('supplier_name', sa.String(255), nullable=True),
        sa.Column('change_type', sa.String(50), nullable=False),
        sa.Column('previous_status', sa.String(255), nullable=True),
        sa.Column('new_status', sa.String(255), nullable=True),
        sa.Column('severity', sa.String(20), default='medium'),
        sa.Column('is_read', sa.Boolean(), default=False),
        sa.Column('email_sent', sa.Boolean(), default=False),
        sa.Column('email_sent_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), default=sa.func.now())
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_alerts')
    op.drop_table('ml_training_logs')
    op.drop_index('idx_snapshots_ruc_date', table_name='company_snapshots')
    op.drop_table('company_snapshots')
    # ### end Alembic commands ###
