"""add_ruc_cache_table

Revision ID: e26ecd8b31fe
Revises: 88024a4663a8
Create Date: 2026-07-07 21:18:26.020001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26ecd8b31fe'
down_revision = '88024a4663a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ruc_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('cached_data', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('last_hit_at', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_ruc_cache_ruc'), 'ruc_cache', ['ruc'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ruc_cache_ruc'), table_name='ruc_cache')
    op.drop_table('ruc_cache')
    # ### end Alembic commands ###
